<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LOGIN</name>
   <tag></tag>
   <elementGuidId>5cb73ddc-85e1-4580-9519-70d13c73756d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.nav-links > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'LOGIN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5949f263-5295-4adc-83b5-0a918cb2b365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Login.html</value>
      <webElementGuid>5b641ad0-082e-4a42-85e0-133cb64c0fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>c2fe3fbe-0695-4e9c-b99c-43f012b39d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[1]/div[@class=&quot;nav-links&quot;]/a[1]</value>
      <webElementGuid>1ea297cd-0bf4-4106-aa75-87e6ebfc0dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LOGIN')]</value>
      <webElementGuid>b7dfe4ec-8c8d-48ba-8f27-6fda9dd09b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STORE'])[1]/preceding::a[1]</value>
      <webElementGuid>204ac911-4bdb-42d7-b34b-37f68c0ac615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRATION'])[1]/preceding::a[2]</value>
      <webElementGuid>bbc49bad-7090-45b5-b168-d6174b685d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>294fb6f3-a5db-4b4b-8b48-0be71aa35fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Login.html')]</value>
      <webElementGuid>7500d359-1b65-4aa7-b94d-b544c5bc4fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/a</value>
      <webElementGuid>e45fb5e5-30c1-4405-b91a-f5e8f17a2b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Login.html' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>80c6ba28-97ca-4ba8-89ae-553cbc969c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
