<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ND_item-link</name>
   <tag></tag>
   <elementGuidId>df0030c1-d386-4eaa-a542-b312112d081a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item.pos1 > a.item-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='carousel']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3bfbd175-d05d-4b59-a109-3b86b771ce05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-link</value>
      <webElementGuid>7303ab65-4818-4b8f-996f-0f3e909e0df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.cyberpunk.net/ca/en/</value>
      <webElementGuid>a193fd20-ed13-4e14-a352-ae93e5417838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>de2dc9ce-5dc6-443d-8ebd-028c9d09ae09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel&quot;)/div[@class=&quot;item pos1&quot;]/a[@class=&quot;item-link&quot;]</value>
      <webElementGuid>0c3d4acc-2387-4155-980b-f648443de787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='carousel']/div[2]/a</value>
      <webElementGuid>7003214d-a24a-4f4e-b20d-19593b0bfd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.cyberpunk.net/ca/en/')])[2]</value>
      <webElementGuid>386b92e6-8895-4805-9617-907d680d55d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>70f7fc88-2df9-428a-8b0e-568ee6b9563b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.cyberpunk.net/ca/en/']</value>
      <webElementGuid>6c47b0ff-a239-4d53-81a4-171bf728b58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
