<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ST_item-link</name>
   <tag></tag>
   <elementGuidId>ad53806e-e45e-418f-9283-efa39a7b3dce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item.pos3 > a.item-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='carousel']/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e158ca0-9822-4867-81a0-45dc09da34f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-link</value>
      <webElementGuid>e286337c-87be-4824-9352-02603f5b60f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://store.ubisoft.com/ca/assassins-creed-shadows/660e5a03fbff4e2940488bcd.html</value>
      <webElementGuid>972613e1-8447-40ea-81e3-446f427c31e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6cd1cfc5-b4e3-4de0-8ab9-659e6131030a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel&quot;)/div[@class=&quot;item pos3&quot;]/a[@class=&quot;item-link&quot;]</value>
      <webElementGuid>153646ff-3b47-41f6-8b95-01db68c4f3a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='carousel']/div[3]/a</value>
      <webElementGuid>5355fe4f-dbeb-4b5f-afd6-317a32379365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://store.ubisoft.com/ca/assassins-creed-shadows/660e5a03fbff4e2940488bcd.html')]</value>
      <webElementGuid>b7e996f5-0f34-4068-b21c-13b1f5520943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>f465ab90-c5f0-4fca-8818-43a4e42b7f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://store.ubisoft.com/ca/assassins-creed-shadows/660e5a03fbff4e2940488bcd.html']</value>
      <webElementGuid>f415fd2f-b7af-4f76-a1a4-33b8134eb676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
