<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Top 3 Best Videogames_item-link</name>
   <tag></tag>
   <elementGuidId>a8f873d6-269e-4173-a2a4-3faff59319e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.item-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='carousel']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0f657e8-9129-404a-a9c3-c9ead60448e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-link</value>
      <webElementGuid>692f1938-45e4-4b8e-ba3c-c422b018b1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.minecraft.net/</value>
      <webElementGuid>7d0c9a76-6775-4efe-b549-a51f9b69fe94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8ec5dc73-0912-43fa-9a16-d1922140dfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel&quot;)/div[@class=&quot;item pos2&quot;]/a[@class=&quot;item-link&quot;]</value>
      <webElementGuid>12359bb4-5c9c-4afd-90c5-c8689d5c463e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='carousel']/div/a</value>
      <webElementGuid>3f7c5538-4751-41fc-99b6-6164220e58d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.minecraft.net/')])[2]</value>
      <webElementGuid>c11a579c-0b30-4bd1-a84e-d4990cedd62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/a</value>
      <webElementGuid>c5e1752a-fa84-46d6-b2ce-1daf4a31b80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.minecraft.net/']</value>
      <webElementGuid>b8fe60b7-bcd1-49e5-ab36-9aca375f315d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
