<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Details (1)</name>
   <tag></tag>
   <elementGuidId>4086d6b6-1935-4bfe-a107-3d7af1e69faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.view-details</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='game-catalog']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d7937d6-9bb7-451d-95fe-e0da7a1e4256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>34b31f38-1b54-496e-b2e7-299f28acf1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product</name>
      <type>Main</type>
      <value>cyberpunk</value>
      <webElementGuid>d9f329a4-717b-4e77-be3d-3e261c9aa7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-details</value>
      <webElementGuid>52c568ff-7ee9-4930-b2e9-3646a91d9f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>70546266-c99c-4b74-abd9-c0e3bd1a1e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;game-catalog&quot;)/div[@class=&quot;product&quot;]/a[@class=&quot;view-details&quot;]</value>
      <webElementGuid>b7b9cb20-dafe-4d91-951a-29b4887c3e31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='game-catalog']/div/a</value>
      <webElementGuid>64355505-5c55-4343-a71f-e5bc518d9f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Details')]</value>
      <webElementGuid>3468c9c5-5b63-4e93-9f79-5eaad42809aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price: $69.99'])[1]/following::a[1]</value>
      <webElementGuid>4b4cd75e-ae05-48a1-887d-f2eb1a3cf575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cyberpunk 2077'])[1]/following::a[1]</value>
      <webElementGuid>275e9a58-fc11-45ae-87a9-d0a41b9a6def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price: $59.99'])[1]/preceding::a[1]</value>
      <webElementGuid>30e8197e-b719-42d9-b410-b40670939d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Details']/parent::*</value>
      <webElementGuid>82291271-3c91-4cc8-b8d6-11dd956ded06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>f357f755-4ea5-4ebc-8dc5-5b61843ce3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/a</value>
      <webElementGuid>08461edd-04f4-4a31-94e5-256d778bdc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>8de6ef78-1441-424e-a276-df969bd43911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
