<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Details_1 (1) (1)</name>
   <tag></tag>
   <elementGuidId>e0f2164c-d451-4a40-8e32-0fd26d0cefd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='game-catalog']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de01afff-f7a7-4a21-aa72-f4f32adda4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>98b8c62a-78c7-4cc4-b264-e0bb3e0aa81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product</name>
      <type>Main</type>
      <value>assassins</value>
      <webElementGuid>f9f534cb-e7f3-461b-a1a0-26ac2b9f7bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-details</value>
      <webElementGuid>1e3722d4-c3eb-4457-a115-dc563310c3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>c6c08e4e-5625-4955-83ae-a824d0173290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;game-catalog&quot;)/div[@class=&quot;product&quot;]/a[@class=&quot;view-details&quot;]</value>
      <webElementGuid>26184736-7dd5-4b86-a8d5-acc11a1c01cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='game-catalog']/div[2]/a</value>
      <webElementGuid>bf07aa97-81c4-46ca-8b0a-e215f21a0fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View Details')])[2]</value>
      <webElementGuid>76efe914-f601-4734-a7df-2d60771ae68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price: $59.99'])[1]/following::a[1]</value>
      <webElementGuid>69bf7d28-135b-450d-aa4c-61d3a7a2ecc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minecraft'])[1]/preceding::a[1]</value>
      <webElementGuid>55f33a52-b27d-48b6-97cf-2068b0779325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price: $29.99'])[1]/preceding::a[1]</value>
      <webElementGuid>640f161e-3569-4c63-bef6-9292df3ada6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>145a23e7-66d7-4120-aa17-481d16e2fa8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>578bd141-f1bd-4674-baae-a9cdabe689d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>db0a5f32-23b9-4819-9b1b-a6577446dc7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
