<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Remove (1)</name>
   <tag></tag>
   <elementGuidId>feafd00e-2040-4f17-8bb4-afb127163649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.remove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='cart-items']/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94dc6bc5-c69d-4507-a662-8023427c2456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove</value>
      <webElementGuid>db595037-c649-437d-a6df-0a1084ffa597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>f7b52a30-346f-4d00-95cc-446512d1742e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-items&quot;)/li[1]/button[@class=&quot;remove&quot;]</value>
      <webElementGuid>b65b594f-fc70-4531-9b85-d92b406325e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cart-items']/li/button</value>
      <webElementGuid>a362934d-7d0c-4ed1-b7d7-b09e32f84355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cyberpunk 2077 - $69.99'])[1]/following::button[1]</value>
      <webElementGuid>4c610529-974e-417e-96ad-5bc7d1e76c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::button[1]</value>
      <webElementGuid>5e2c14b6-bb3b-4d80-aefe-8451f756b352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/preceding::button[1]</value>
      <webElementGuid>27999864-b5b2-4521-bf64-abf0564c22be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>6f0bb2d2-cd8a-4e54-973d-8bc7751b0d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>290d4812-cec7-4573-9b58-c1bbe1151593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>a45df7c5-b76e-4c5c-897a-62e041ee3204</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
