<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_6</name>
   <tag></tag>
   <elementGuidId>51f25945-3536-48c7-ab03-9bf30693b416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sponsors2-logos > a:nth-of-type(2) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Mojang2020Logo.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b4696c03-8696-4eb2-a8a1-310d36dccd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Mojang2020Logo.png</value>
      <webElementGuid>4023dce1-97c8-4313-9410-343845b7a730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;sponsors2&quot;]/div[@class=&quot;sponsors2-logos&quot;]/a[2]/img[1]</value>
      <webElementGuid>72778234-dfc4-4352-9e26-c36328398ae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Mojang2020Logo.png')]</value>
      <webElementGuid>da730ec3-4985-4b32-93c3-d4c24e432108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]/img</value>
      <webElementGuid>6a384d75-4d2b-483d-9d9c-89da2cd669c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Mojang2020Logo.png']</value>
      <webElementGuid>c27139c3-9f86-4beb-9409-d32f4f8dd974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
