<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_5</name>
   <tag></tag>
   <elementGuidId>7a401d6b-de03-47c5-a263-c453f8ff96a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sponsors2-logos > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.cdprojektred.com/build/images/img/logo-5eac85f8.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ec4d3326-ca87-4fa9-93c3-76271e6742d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.cdprojektred.com/build/images/img/logo-5eac85f8.svg</value>
      <webElementGuid>3635b0ab-db34-439f-b929-823fe9537f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;sponsors2&quot;]/div[@class=&quot;sponsors2-logos&quot;]/a[1]/img[1]</value>
      <webElementGuid>1ecc877b-2959-486d-8e0b-7d41f06aced3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.cdprojektred.com/build/images/img/logo-5eac85f8.svg')]</value>
      <webElementGuid>2d2495fa-4045-4d17-b30f-dbcfa5553454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>c70a49fa-061a-40a4-bc97-5c359937494c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.cdprojektred.com/build/images/img/logo-5eac85f8.svg']</value>
      <webElementGuid>c16bc275-fbee-4323-8a06-20778afc356c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
