<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>d309b90b-8944-419b-9901-6eff9131b3a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Assassin's Creed Valhalla&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='game-catalog']/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ae3b656-a702-4e73-a9c3-f1e5ef9106f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://upload.wikimedia.org/wikipedia/en/f/ff/Assassin%27s_Creed_Valhalla_cover.jpg</value>
      <webElementGuid>7d97b3b5-6f95-4a01-9381-052655829eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;game-catalog&quot;)/div[@class=&quot;product&quot;]/img[1]</value>
      <webElementGuid>f99f57e3-416f-4986-b33b-ec0a7e9a111a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Assassin's Creed Valhalla</value>
      <webElementGuid>b0764633-5860-4951-a8fc-d0657f66744e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='game-catalog']/div[2]/img</value>
      <webElementGuid>99c8fac6-431a-448a-9240-1430e5934936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;Assassin's Creed Valhalla&quot;]</value>
      <webElementGuid>f46556bb-2f09-40c3-9d56-66c1b31b19ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>260e25a0-e900-4f97-946c-28a23094050a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://upload.wikimedia.org/wikipedia/en/f/ff/Assassin%27s_Creed_Valhalla_cover.jpg' and @alt = concat(&quot;Assassin&quot; , &quot;'&quot; , &quot;s Creed Valhalla&quot;)]</value>
      <webElementGuid>593b6849-55a6-4322-adca-4ca6ea65d357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.thewitcher.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fen.9f8828c0.png&amp;w=640&amp;q=75')]</value>
      <webElementGuid>cfdca73a-98f2-4656-96b4-3fac28112b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>033da4c2-9e56-474b-bb96-88526537f5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.thewitcher.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fen.9f8828c0.png&amp;w=640&amp;q=75']</value>
      <webElementGuid>ded46299-6616-4779-a58e-61a252d1425b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
