<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_3</name>
   <tag></tag>
   <elementGuidId>c3b80f55-5c72-4f51-9127-00973ad58c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.cyberpunk.net/build/images/logo-en-ed943f1c.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f9d3cac-919a-4c4d-8efd-98d0d6768257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.cyberpunk.net/build/images/logo-en-ed943f1c.png</value>
      <webElementGuid>c4f16092-b898-41e8-bf84-7dd356706a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;sponsors&quot;]/div[@class=&quot;sponsor-links&quot;]/a[@class=&quot;sponsor-Menu1&quot;]/img[1]</value>
      <webElementGuid>fb74d45d-7a44-493f-8231-a967ff5cfab8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.cyberpunk.net/build/images/logo-en-ed943f1c.png')]</value>
      <webElementGuid>35abd285-5b66-4e94-ac47-b466911d5edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>2115355a-4904-4839-bfca-198521899123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.cyberpunk.net/build/images/logo-en-ed943f1c.png']</value>
      <webElementGuid>24372c59-4706-436a-a68e-9e3278438dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
