<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_4</name>
   <tag></tag>
   <elementGuidId>0910bd2c-b390-4858-98ad-9da831667617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(6) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.upsellit.com/w:760/format:webp/d/13865/HumbleBundle-TT-11-2025-urgency-precart-dsktp-3x.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b83a4eac-cb16-4206-9c52-bbd67df7ea79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.upsellit.com/w:760/format:webp/d/13865/HumbleBundle-TT-11-2025-urgency-precart-dsktp-3x.webp</value>
      <webElementGuid>6727814f-657a-47f1-9771-d7372d02f904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;wrapperPage&quot;]/div[@class=&quot;topGrid&quot;]/aside[@class=&quot;asideSection&quot;]/a[6]/img[1]</value>
      <webElementGuid>f0fef411-dea8-4283-afd7-33488a7840e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.upsellit.com/w:760/format:webp/d/13865/HumbleBundle-TT-11-2025-urgency-precart-dsktp-3x.webp')]</value>
      <webElementGuid>74662e0f-ce41-47d1-966b-8a332c2d79b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/img</value>
      <webElementGuid>c487ddef-65d0-494c-aeeb-da21eee20fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.upsellit.com/w:760/format:webp/d/13865/HumbleBundle-TT-11-2025-urgency-precart-dsktp-3x.webp']</value>
      <webElementGuid>e8f6da43-99c2-49a2-9dd2-fa178776228b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
