<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_loginEmail</name>
   <tag></tag>
   <elementGuidId>896ece1b-71b3-4db2-a3f2-c9c332271921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d44fca1-e374-4c2c-8879-b84ce4ffb1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e103ee96-5e8b-40f4-b38e-acd5de0d2446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginEmail</value>
      <webElementGuid>320cabec-5a32-4958-92be-7d7b591efdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. user@gmail.com</value>
      <webElementGuid>27d3e0e7-2134-44b7-abe2-fd036ebec00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginEmail&quot;)</value>
      <webElementGuid>f1499cca-8bf6-4220-aa94-4a848bd165e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginEmail']</value>
      <webElementGuid>f5589357-1501-4928-bc9c-582ca02528be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div/input</value>
      <webElementGuid>245f4640-8c6d-4387-b610-ac7c937148f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>715b4170-4a81-4079-a9f2-8d2e2560957b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'loginEmail' and @placeholder = 'e.g. user@gmail.com']</value>
      <webElementGuid>21fde3d0-9e8d-41e5-9f4b-9b8d9782bf31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
