<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nickname_nickname</name>
   <tag></tag>
   <elementGuidId>9d524ddc-c7e4-432c-bdfc-266b641467dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nickname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nickname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7e65448-6924-4018-a8b7-a5e9b90d2bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b064897f-5be2-4465-82fd-8a4c95a06f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nickname</value>
      <webElementGuid>acb93dbf-c9a0-4f50-912f-b83ebfc5712d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nickname</value>
      <webElementGuid>16485bb2-9d39-45aa-9c72-f8215574de8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>540ec48a-da6b-4d9c-958c-2f3c6ecf7fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Jopoarma</value>
      <webElementGuid>21694279-3656-4b54-80a2-11f855eacd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nickname&quot;)</value>
      <webElementGuid>06cf6911-75de-404b-a645-28f9a9ebe7f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nickname']</value>
      <webElementGuid>783a497e-1a93-471d-a4fa-978d7e682155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registrationForm']/div[4]/input</value>
      <webElementGuid>958b733f-4443-43ea-9d1a-20086cd4c25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>50aa8723-3abd-4ccb-8359-d27b80206e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nickname' and @name = 'nickname' and @placeholder = 'e.g. Jopoarma']</value>
      <webElementGuid>1c9dcb02-df9d-4242-b4df-caf796bead59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
