<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_emailReg (1)</name>
   <tag></tag>
   <elementGuidId>23542b5c-c7d5-43cf-950d-36d62387f70f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailReg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailReg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b993a72a-9d8b-4275-9c75-e96129f771f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5e18069c-55ed-4d4d-af0d-fd51f767d349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailReg</value>
      <webElementGuid>b9685819-d260-40c6-a7b8-211f2702aae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailReg</value>
      <webElementGuid>62b2c423-725b-45e0-9087-19d9c0912da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. user@gmail.com</value>
      <webElementGuid>30089568-7167-4d5f-8f95-4da4ef2a697c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailReg&quot;)</value>
      <webElementGuid>2e52e577-4fac-4877-b017-9715af4d9d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailReg']</value>
      <webElementGuid>f5b0672a-f8ba-4663-af10-2d1f7968843c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registrationForm']/div[6]/input</value>
      <webElementGuid>81dd37b8-d1b5-45e0-962b-b4ab048aac27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>b5b5a5bd-839e-494e-bb7e-8baca8c3aafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailReg' and @name = 'emailReg' and @placeholder = 'e.g. user@gmail.com']</value>
      <webElementGuid>45e66eaa-44b0-4ef6-a671-6d25512660cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
