<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_emailReg</name>
   <tag></tag>
   <elementGuidId>75350828-ec48-48c7-b401-bc494d8b82cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailReg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailReg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c7d55fb-503f-4384-810d-7cb381a29c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>96e05aa2-0403-4646-8ce8-43325a06b42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailReg</value>
      <webElementGuid>145c31a8-74d7-41d1-b838-ccf2fafc2b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailReg</value>
      <webElementGuid>5d0df6e4-fca2-4e32-ad38-baf07bd57b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. user@gmail.com</value>
      <webElementGuid>bb7ad790-c6e3-4bc7-8950-eb63796a3a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailReg&quot;)</value>
      <webElementGuid>ef22c21a-49a4-4749-8c50-f50cc721e7b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailReg']</value>
      <webElementGuid>bd008af2-f32a-4d2f-a024-269cc7e12f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registrationForm']/div[6]/input</value>
      <webElementGuid>a25a67e5-4de3-4d5b-a859-d8f642e9aa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>14aa8702-0cb1-42e4-81ee-91e1206c76c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailReg' and @name = 'emailReg' and @placeholder = 'e.g. user@gmail.com']</value>
      <webElementGuid>e912cc05-d6ff-4886-9ef7-196ec8c00b32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
