<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ (3)</name>
   <tag></tag>
   <elementGuidId>48b78633-d044-4c56-8d63-185dbd795c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1de0524-f55b-4c00-af47-f9187b87b470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>8113e2ca-4c81-4cdc-a177-e05ca90f68d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>613197cf-d66d-4745-a806-6afe4e7ab20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;modal-content&quot;]/span[@class=&quot;close&quot;]</value>
      <webElementGuid>e19a0ff7-0118-4439-b5cc-ff118bd07a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div/span</value>
      <webElementGuid>0a740ce5-2ce9-40a4-82bb-7fb43adc61a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price: $59.99'])[4]/following::span[1]</value>
      <webElementGuid>2aa17d42-5440-46b7-8ec1-5c718ab34eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cyberpunk 2077'])[2]/preceding::span[1]</value>
      <webElementGuid>4f35961b-d3e7-4c76-9383-798a2c466ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>ca1b9a59-0bd8-4e04-9609-49e0934c2080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/span</value>
      <webElementGuid>60e40d55-c421-4549-a663-475ee7de4b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>b5aa17f9-eaee-4c52-b987-f8f15fa67376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
